name: Deploy to GitHub Pages

on:
  push:
    branches:
      - all-blocks

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: utooland/setup-utoo@v1
      - run: ut
      - run: ut build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: preview.pro.ant.design
