name: Preview Deploy

on:
  workflow_run:
    workflows: ['Preview Build']
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      actions: read # for dawidd6/action-download-artifact to query and download artifacts
      checks: write # for surge-preview to publish the deployment as a commit check run
      issues: write # for surge-preview to modify or create issue comments
      pull-requests: write # for surge-preview to modify or create PR comments
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: download dist artifact
        uses: dawidd6/action-download-artifact@b6e2e70617bc3265edd6dab6c906732b2f1ae151 # v21
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: dist
          path: dist

      - name: Deploy to Surge
        uses: afc163/surge-preview@bf90a5a86111f6311ca42f0a5a0f80fb0fb03cec # v1.13.0
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build: echo done
          dist: dist
          failOnError: true
          teardown: false # preview sites are not torn down automatically
          screenshot: true
          lighthouse: true
          setCommitStatus: true
        env:
          PAGESPEED_API_KEY: ${{ secrets.PAGESPEED_API_KEY }}
