name: 🏥 React Doctor

on: push

permissions:
  contents: read
  pull-requests: write

jobs:
  react-doctor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22
      - uses: millionco/react-doctor@6543a86f9dfe86c894bd71361fc2c46d8d9c967d # main
        with:
          diff: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
